name: Build and Deploy to EC2

on:
  workflow_dispatch: # Allow manual trigger through GitHub UI

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with Docker Compose
        run: |
          ssh -T ${{ secrets.USERNAME }}@${{ secrets.HOST }} << EOF
            cd /pHRma
            git pull
            docker-compose down
            docker-compose up --build -d
          EOF
